"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { ArrowDownLeft, ArrowUpRight, Search } from "lucide-react"

// Mock transaction data for high-net-worth individual
const transactions = [
  {
    id: "1",
    name: "Private Equity Investment - Tech Startup",
    date: "Apr 7, 2023",
    amount: "-£50,000.00",
    type: "expense",
  },
  {
    id: "2",
    name: "Dividend Income - Luxury Brand Holdings",
    date: "Apr 6, 2023",
    amount: "+£250,000.00",
    type: "income",
  },
  {
    id: "3",
    name: "Yacht Maintenance - Superyacht 'Elegance'",
    date: "Apr 5, 2023",
    amount: "-£120,000.00",
    type: "expense",
  },
  {
    id: "4",
    name: "Fine Art Auction - Impressionist Masterpiece",
    date: "Apr 4, 2023",
    amount: "-£350,000.00",
    type: "expense",
  },
  {
    id: "5",
    name: "Venture Capital Exit - AI Startup",
    date: "Apr 3, 2023",
    amount: "+£120,000.00",
    type: "income",
  },
  {
    id: "6",
    name: "Charitable Donation - Education Foundation",
    date: "Apr 2, 2023",
    amount: "-£100,000.00",
    type: "expense",
  },
  {
    id: "7",
    name: "Business Revenue - Luxury Property Development",
    date: "Apr 1, 2023",
    amount: "+£850,000.00",
    type: "income",
  },
  {
    id: "8",
    name: "Wealth Management Fee - Q1 2023",
    date: "Mar 31, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "9",
    name: "Wine Collection Expansion",
    date: "Mar 30, 2023",
    amount: "-£150,000.00",
    type: "expense",
  },
  {
    id: "10",
    name: "Property Sale - Beverly Hills Estate",
    date: "Mar 29, 2023",
    amount: "+£450,000.00",
    type: "income",
  },
  {
    id: "11",
    name: "Private Jet Maintenance",
    date: "Mar 28, 2023",
    amount: "-£850,000.00",
    type: "expense",
  },
  {
    id: "12",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 27, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "13",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 26, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "14",
    name: "Luxury Car Collection - New Acquisition",
    date: "Mar 25, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "15",
    name: "Charitable Donation - Medical Research",
    date: "Mar 24, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "16",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Mar 23, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "17",
    name: "Property Purchase - Monaco",
    date: "Mar 22, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "18",
    name: "Art Collection Expansion",
    date: "Mar 21, 2023",
    amount: "-£450,000.00",
    type: "expense",
  },
  {
    id: "19",
    name: "Stock Portfolio Growth",
    date: "Mar 20, 2023",
    amount: "+£700,000.00",
    type: "income",
  },
  {
    id: "20",
    name: "Private Equity Dividend",
    date: "Mar 19, 2023",
    amount: "+£150,000.00",
    type: "income",
  },
  {
    id: "21",
    name: "Charitable Donation - Arts Foundation",
    date: "Mar 18, 2023",
    amount: "-£750,000.00",
    type: "expense",
  },
  {
    id: "22",
    name: "Business Revenue - Luxury Yacht Tours",
    date: "Mar 17, 2023",
    amount: "+£550,000.00",
    type: "income",
  },
  {
    id: "23",
    name: "Property Sale - London Mayfair",
    date: "Mar 16, 2023",
    amount: "+£350,000.00",
    type: "income",
  },
  {
    id: "24",
    name: "Venture Capital Investment - Biotech",
    date: "Mar 15, 2023",
    amount: "-£600,000.00",
    type: "expense",
  },
  {
    id: "25",
    name: "Wine Collection Expansion",
    date: "Mar 14, 2023",
    amount: "-£200,000.00",
    type: "expense",
  },
  {
    id: "26",
    name: "Private Jet Charter - Business Trip",
    date: "Mar 13, 2023",
    amount: "-£120,000.00",
    type: "expense",
  },
  {
    id: "27",
    name: "Business Revenue - Luxury Hotel Chain",
    date: "Mar 12, 2023",
    amount: "+£120,000.00",
    type: "income",
  },
  {
    id: "28",
    name: "Property Purchase - Swiss Alps",
    date: "Mar 11, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "29",
    name: "Charitable Donation - Education",
    date: "Mar 10, 2023",
    amount: "-£100,000.00",
    type: "expense",
  },
  {
    id: "30",
    name: "Stock Portfolio Growth",
    date: "Mar 9, 2023",
    amount: "+£850,000.00",
    type: "income",
  },
  {
    id: "31",
    name: "Venture Capital Investment - AI Startup",
    date: "Mar 8, 2023",
    amount: "-£500,000.00",
    type: "expense",
  },
  {
    id: "32",
    name: "Business Revenue - Luxury Fashion Brand",
    date: "Mar 7, 2023",
    amount: "+£900,000.00",
    type: "income",
  },
  {
    id: "33",
    name: "Property Sale - Hamptons Estate",
    date: "Mar 6, 2023",
    amount: "+£220,000.00",
    type: "income",
  },
  {
    id: "34",
    name: "Wealth Management Fee - Q1 2023",
    date: "Mar 5, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "35",
    name: "Wine Collection Expansion",
    date: "Mar 4, 2023",
    amount: "-£150,000.00",
    type: "expense",
  },
  {
    id: "36",
    name: "Private Jet Maintenance",
    date: "Mar 3, 2023",
    amount: "-£850,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "43",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "43",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "44",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "45",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "46",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "47",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "48",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "49",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "50",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "51",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "52",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "53",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "54",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "37",
    name: "Stock Portfolio Rebalancing",
    date: "Mar 2, 2023",
    amount: "-£250,000.00",
    type: "expense",
  },
  {
    id: "38",
    name: "Venture Capital Investment - Fintech",
    date: "Mar 1, 2023",
    amount: "-£400,000.00",
    type: "expense",
  },
  {
    id: "39",
    name: "Luxury Car Collection - New Acquisition",
    date: "Feb 28, 2023",
    amount: "-£180,000.00",
    type: "expense",
  },
  {
    id: "40",
    name: "Charitable Donation - Medical Research",
    date: "Feb 27, 2023",
    amount: "-50,000.00",
    type: "expense",
  },
  {
    id: "41",
    name: "Business Revenue - Luxury Watch Brand",
    date: "Feb 26, 2023",
    amount: "+£650,000.00",
    type: "income",
  },
  {
    id: "42",
    name: "Property Purchase - Monaco",
    date: "Feb 25, 2023",
    amount: "-£250,000.00",
    type: "expense",
  }
]

export default function TransactionList() {
  const [searchQuery, setSearchQuery] = useState("")

  const filteredTransactions = transactions.filter((transaction) =>
    transaction.name.toLowerCase().includes(searchQuery.toLowerCase())
  )

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle>Recent Transactions</CardTitle>
        <div className="relative w-64">
          <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500" />
          <Input
            placeholder="Search transactions..."
            className="pl-8"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
        </div>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {filteredTransactions.length > 0 ? (
            filteredTransactions.map((transaction) => (
              <div key={transaction.id} className="flex items-center justify-between p-3 rounded-lg hover:bg-gray-50">
                <div className="flex items-center space-x-4">
                  <div
                    className={`rounded-full p-2 £{
                      transaction.type === "income" ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"
                    }`}
                  >
                    {transaction.type === "income" ? (
                      <ArrowDownLeft className="h-4 w-4" />
                    ) : (
                      <ArrowUpRight className="h-4 w-4" />
                    )}
                  </div>
                  <div>
                    <p className="font-medium">{transaction.name}</p>
                    <p className="text-sm text-gray-500">{transaction.date}</p>
                  </div>
                </div>
                <div className={`font-medium £{transaction.type === "income" ? "text-green-600" : "text-gray-900"}`}>
                  {transaction.amount}
                </div>
              </div>
            ))
          ) : (
            <div className="text-center py-6 text-gray-500">No transactions found</div>
          )}
        </div>
      </CardContent>
    </Card>
  )
}
